[package]
name = "ic-news"
version = "0.0.1"
description = "IC News Motoko"
repository = "https://github.com/ic-news/ic-news-mo"
keywords = [ "ic", "news", "motoko" ]
license = "MIT"

[dependencies]
ic-certification = "0.1.3"
sha2 = "0.1.0"
cbor = "1.0.0"
base = "0.14.1"
ic-websocket-cdk = "0.4.1"
itertools = "0.1.0"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main@4781cb03efd34b124c22396c69710b374366c797"
# StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
